Repository web3bio/web3bio-profile-api, pull requests merged in 2023-05, with the labels that each got.

#7 Staging
  middleware.ts
  pages/api/profile/ens/[handle].ts
  pages/api/profile/lens/[handle].ts
  utils/ens.ts
  utils/resolver.ts
Labels: bug

#8 fix: empty handle
  utils/resolver.ts
Labels: bug

#13 Staging
  next.config.js
  pages/api/profile/ens/[handle].ts
  utils/cointype.ts
  utils/fetcher.ts
  utils/resolver.ts
Labels: enhancement

#15 Fix ERC1155 NFT issue
  pages/api/profile/ens/[handle].ts
  utils/resolver.ts
Labels: bug

#17 Fix avatar fetching error
  pages/api/profile/ens/[handle].ts
  utils/resolver.ts
Labels: bug

#19 Fix avatar issue
  pages/api/profile/ens/[handle].ts
  pages/api/profile/farcaster/[handle].ts
  pages/api/profile/lens/[handle].ts
  pages/api/profile/twitter/[handle].ts
  utils/base.ts
Labels: bug, enhancement

#21 Improve API code and error message
  README.md
  pages/api/profile/ens/[handle].ts
  pages/api/profile/farcaster/[handle].ts
  pages/api/profile/lens/[handle].ts
  pages/api/profile/twitter/[handle].ts
  tailwind.config.js
  utils/base.ts
  utils/dotbit/[handle].ts
  utils/platform.ts
  utils/regexp.ts
Labels: bug, enhancement

#23 Add ETH query to Lens and Farcaster
  pages/api/profile/farcaster/[handle].ts
  pages/api/profile/lens/[handle].ts
  utils/lens.ts
Labels: enhancement
